name: "Micro Rust Action"
description: "A minimal Rust-based GitHub Action that echoes Hello World"
author: "NicoKNL"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "message-circle"
  color: "orange"
