name: Test Micro Rust Action

on:
  push:
    branches: [main, setup]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Micro Rust Action
        uses: ./
